compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
dotenv: .env
wallets :
   from_key: ${PRIVATE_KEY}
      